version: "3.8"

services:
  postgres:
    image: postgres:13-bullseye
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kp
  backend:
    depends_on:
      - postgres
    build: ./backend
    restart: always
    container_name: backend
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: kp
      DB_PORT: 5432
    command: >
      bash -c " 
        python manage.py wait_for_db
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
  frontend:
    depends_on:
      - postgres
      - backend
    build: ./frontend
    restart: always
    container_name: frontend
    command: >
      bash -c "npm run dev"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
