# Generated by Django 3.2.9 on 2021-12-20 03:02

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='access_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='expires_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='token_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='expires',
            field=models.DateTimeField(),
        ),
    ]
