# Generated by Django 3.2.9 on 2021-12-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211225_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='oauth_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='oauth_token_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='session_state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
