# Generated by Django 3.2.9 on 2021-12-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_account_id_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='refresh_token_expires_in',
            field=models.IntegerField(null=True),
        ),
    ]
