# Generated by Django 3.2.9 on 2021-11-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintball', '0003_auto_20201016_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
