# Generated by Django 3.2.9 on 2021-11-26 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintball', '0004_alter_item_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
