# Generated by Django 3.2.9 on 2021-11-27 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintball', '0006_item_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
    ]
